version: "3.8"
services:
  flask-backend:
    build:
      context: .  # Build from the root directory
      dockerfile: Dockerfile.flask  # Use the Flask Dockerfile
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
    network_mode: host
    volumes:
      - .:/app  # Mount the entire repository for live updates
    environment:
      - FLASK_ENV=development  # Set Flask environment (optional)
    working_dir: /app  # Set the working directory explicitly

  node-frontend:
    build:
      context: .  # Build from the root directory
      dockerfile: Dockerfile.node  # Use the Node.js Dockerfile
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    network_mode: host
    volumes:
      - .:/app  # Mount the entire repository for live updates
    environment:
      - NODE_ENV=development  # Set Node.js environment (optional)
    depends_on:
      - flask-backend  # Ensure the Flask backend starts first
    working_dir: /app